#!/usr/bin/env node
/* ============================================
   Carunel — Build Script
   ============================================
   The site itself is plain static HTML/CSS/JS with no bundler — nothing
   here transforms markup, styles, or scripts. This script exists for one
   reason: to let CI (see .github/workflows/pages.yml) inject the public
   FORMSPREE_FORM_ID environment variable into js/config.js at deploy
   time, so a real form ID never has to be hand-edited or committed.

   It copies the site as-is into dist/, then overwrites dist/js/config.js
   with the value of process.env.FORMSPREE_FORM_ID (or an empty string if
   unset, which keeps the inquiry form hidden — see js/main.js).

   Usage:
     node build.js
     FORMSPREE_FORM_ID=your-form-id node build.js
     npm run build
     FORMSPREE_FORM_ID=your-form-id npm run build

   Local development does not require this script — editing js/config.js
   directly (see .env.example) works fine for a plain static-file server. */

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const OUT_DIR = path.join(ROOT, 'dist');

// Top-level entries that are part of the published site. Everything else
// (tooling, git metadata, editor config, local env files) is left out of
// dist/ on purpose.
const INCLUDE = [
  '404.html',
  'about',
  'about.html',
  'assets',
  'beadwell',
  'beadwell-words',
  'books-media',
  'CNAME',
  'contact',
  'contact.html',
  'css',
  'gentleclover',
  'index.html',
  'js',
  'organizations',
  'privacy',
  'products',
  'products.html',
  'quizwell',
  'robots.txt',
  'sitemap.xml'
];

function clean(dir) {
  fs.rmSync(dir, { recursive: true, force: true });
  fs.mkdirSync(dir, { recursive: true });
}

function copySite() {
  clean(OUT_DIR);
  for (const entry of INCLUDE) {
    const src = path.join(ROOT, entry);
    if (!fs.existsSync(src)) continue; // e.g. beadwell-memory/ is gitignored, may not exist in CI
    fs.cpSync(src, path.join(OUT_DIR, entry), { recursive: true });
  }
}

function writeConfig() {
  const formId = process.env.FORMSPREE_FORM_ID || '';
  const configPath = path.join(OUT_DIR, 'js', 'config.js');
  const contents = `/* ============================================
   Carunel — Build Configuration (generated)
   ============================================
   Generated by build.js from the FORMSPREE_FORM_ID environment variable.
   Do not hand-edit this file in dist/ — edit js/config.js (the source)
   or set FORMSPREE_FORM_ID before building instead. See README.md and
   .env.example for details. */
window.CARUNEL_CONFIG = {
  FORMSPREE_FORM_ID: ${JSON.stringify(formId)}
};
`;
  fs.writeFileSync(configPath, contents);
  return formId;
}

function main() {
  copySite();
  const formId = writeConfig();
  const state = formId ? `configured (${formId})` : 'unconfigured — inquiry form hidden';
  console.log(`Built site to ${path.relative(ROOT, OUT_DIR)}/ — FORMSPREE_FORM_ID ${state}`);
}

main();
